"""Tests for the generated-file detection added to FileAnalyzer.

We hit `_looks_generated` directly to keep tests fast and free of `rich` /
ConfigManager dependencies.
"""

import unittest


class TestLooksGenerated(unittest.TestCase):
    def setUp(self):
        try:
            from ..analyzers.file_analyzer import FileAnalyzer
        except ModuleNotFoundError:
            self.skipTest("FileAnalyzer deps not installed")
        self.analyzer = FileAnalyzer(debug=False)

    def test_at_generated_marker_skipped(self):
        sample = b"// @generated by some-tool\nconst x = 1\n"
        self.assertTrue(self.analyzer._looks_generated(sample, "x.js"))

    def test_do_not_edit_marker_skipped(self):
        sample = b"// DO NOT EDIT - this file is auto-generated\nfoo\n"
        self.assertTrue(self.analyzer._looks_generated(sample, "x.js"))

    def test_sourcemap_skipped(self):
        sample = b'{"version":3,"sources":["a.ts"],"mappings":"AAAA"}'
        self.assertTrue(self.analyzer._looks_generated(sample, "bundle.js.map"))

    def test_minified_single_line_skipped(self):
        # 4kB+ with no newline
        sample = b"!function(){var a=1,b=2;return a+b}();" * 200
        self.assertTrue(self.analyzer._looks_generated(sample, "bundle.min.js"))

    def test_long_avg_line_skipped(self):
        # A few newlines but average line is very long.
        line = b"x" * 1500 + b"\n"
        sample = line * 4
        self.assertTrue(self.analyzer._looks_generated(sample, "bundle.min.js"))

    def test_normal_source_kept(self):
        sample = (
            b"import os\n"
            b"\n"
            b"def main():\n"
            b"    print('hello')\n"
            b"\n"
            b"if __name__ == '__main__':\n"
            b"    main()\n"
        )
        self.assertFalse(self.analyzer._looks_generated(sample, "main.py"))


if __name__ == "__main__":
    unittest.main()
