"""v1 baseline schema

Revision ID: b6a211ad2270
Revises: 
Create Date: 2026-05-20 01:41:10.206214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('directory_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('analyzed_at', sa.DateTime(), nullable=False),
    sa.Column('total_projects', sa.Integer(), nullable=False),
    sa.Column('total_files', sa.Integer(), nullable=False),
    sa.Column('total_lines', sa.Integer(), nullable=False),
    sa.Column('total_code_lines', sa.Integer(), nullable=False),
    sa.Column('total_functions', sa.Integer(), nullable=False),
    sa.Column('total_classes', sa.Integer(), nullable=False),
    sa.Column('filters_applied', sa.JSON(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('analyses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analyses_directory_path'), ['directory_path'], unique=False)
        batch_op.create_index(batch_op.f('ix_analyses_status'), ['status'], unique=False)

    op.create_table('project_notes',
    sa.Column('path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('path')
    )
    op.create_table('recent_paths',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_used', sa.DateTime(), nullable=False),
    sa.Column('use_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recent_paths', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recent_paths_path'), ['path'], unique=True)

    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('color', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tags_name'), ['name'], unique=True)

    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysis_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('total_dirs', sa.Integer(), nullable=False),
    sa.Column('total_files', sa.Integer(), nullable=False),
    sa.Column('total_lines', sa.Integer(), nullable=False),
    sa.Column('code_lines', sa.Integer(), nullable=False),
    sa.Column('comment_lines', sa.Integer(), nullable=False),
    sa.Column('blank_lines', sa.Integer(), nullable=False),
    sa.Column('characters', sa.Integer(), nullable=False),
    sa.Column('words', sa.Integer(), nullable=False),
    sa.Column('functions', sa.Integer(), nullable=False),
    sa.Column('classes', sa.Integer(), nullable=False),
    sa.Column('todos', sa.Integer(), nullable=False),
    sa.Column('imports', sa.Integer(), nullable=False),
    sa.Column('languages', sa.JSON(), nullable=True),
    sa.Column('avg_lines_per_file', sa.Float(), nullable=False),
    sa.Column('test_files', sa.Integer(), nullable=False),
    sa.Column('test_total_lines', sa.Integer(), nullable=False),
    sa.Column('test_code_lines', sa.Integer(), nullable=False),
    sa.Column('repo_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_commit_at', sa.DateTime(), nullable=True),
    sa.Column('todo_items', sa.JSON(), nullable=True),
    sa.Column('dependencies', sa.JSON(), nullable=True),
    sa.Column('complex_functions', sa.JSON(), nullable=True),
    sa.Column('jsx_components', sa.Integer(), nullable=False),
    sa.Column('react_hooks', sa.Integer(), nullable=False),
    sa.Column('async_functions', sa.Integer(), nullable=False),
    sa.Column('interfaces', sa.Integer(), nullable=False),
    sa.Column('type_aliases', sa.Integer(), nullable=False),
    sa.Column('enums', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projects_analysis_id'), ['analysis_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_last_commit_at'), ['last_commit_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_name'), ['name'], unique=False)

    op.create_table('project_flags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('flag_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('project_flags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_flags_flag_type'), ['flag_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_flags_project_id'), ['project_id'], unique=False)

    op.create_table('project_tags',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id', 'tag_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_tags')
    with op.batch_alter_table('project_flags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_flags_project_id'))
        batch_op.drop_index(batch_op.f('ix_project_flags_flag_type'))

    op.drop_table('project_flags')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_name'))
        batch_op.drop_index(batch_op.f('ix_projects_last_commit_at'))
        batch_op.drop_index(batch_op.f('ix_projects_analysis_id'))

    op.drop_table('projects')
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tags_name'))

    op.drop_table('tags')
    with op.batch_alter_table('recent_paths', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recent_paths_path'))

    op.drop_table('recent_paths')
    op.drop_table('project_notes')
    with op.batch_alter_table('analyses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analyses_status'))
        batch_op.drop_index(batch_op.f('ix_analyses_directory_path'))

    op.drop_table('analyses')
    # ### end Alembic commands ###
